$ErrorActionPreference = "Stop"

Write-Host "1. Установите PostgreSQL 16 или 17 с официального сайта:"
Write-Host "   https://www.postgresql.org/download/windows/"
Write-Host ""
Write-Host "2. Создайте базу и пользователя в pgAdmin или psql:"
Write-Host "   CREATE USER ppr_user WITH PASSWORD 'СЛОЖНЫЙ_ПАРОЛЬ';"
Write-Host "   CREATE DATABASE ppr_control OWNER ppr_user;"
Write-Host ""
Write-Host "3. Выполните schema.sql:"
Write-Host "   psql -U ppr_user -d ppr_control -f schema.sql"
Write-Host ""
Write-Host "4. Скопируйте .env.example в .env и укажите пароль."
Write-Host "5. Выполните npm install, затем миграцию из рабочего db.json."
